version: "3.1"
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    extra_hosts:
      - host.docker.internal:host-gateway
