version: "3.7"
services:
  influxdb:
    image: influxdb:2.1.1
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./data:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
